name: antam
description: "An Tam Nghe - Mobile App"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_contacts: ^1.1.9
  permission_handler: ^11.4.0

  
  # Firebase
  firebase_core: ^2.30.0
  cloud_firestore: ^4.15.0
  firebase_auth: ^4.17.4
  
  # Local storage
  shared_preferences: ^2.2.2

  # UI
  cupertino_icons: ^1.0.6
  font_awesome_flutter: ^10.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
