// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1XtqFY8oewG0khCPIJA5cW3UnKIMyRoE',
    appId: '1:919198194330:web:6fa4f719ed3b3b03185d23',
    messagingSenderId: '919198194330',
    projectId: 'an-tam-nghe-5d962',
    authDomain: 'an-tam-nghe-5d962.firebaseapp.com',
    storageBucket: 'an-tam-nghe-5d962.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA99vHc6c6Y4tNOONGYcdCV90dErUcGWzE',
    appId: '1:919198194330:android:b16aae82a16b326c185d23',
    messagingSenderId: '919198194330',
    projectId: 'an-tam-nghe-5d962',
    storageBucket: 'an-tam-nghe-5d962.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1OlA3vURiiGYxxwxIXQ5euyELwdsG27M',
    appId: '1:919198194330:ios:bb33290320971653185d23',
    messagingSenderId: '919198194330',
    projectId: 'an-tam-nghe-5d962',
    storageBucket: 'an-tam-nghe-5d962.firebasestorage.app',
    iosBundleId: 'com.example.antam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1OlA3vURiiGYxxwxIXQ5euyELwdsG27M',
    appId: '1:919198194330:ios:bb33290320971653185d23',
    messagingSenderId: '919198194330',
    projectId: 'an-tam-nghe-5d962',
    storageBucket: 'an-tam-nghe-5d962.firebasestorage.app',
    iosBundleId: 'com.example.antam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1XtqFY8oewG0khCPIJA5cW3UnKIMyRoE',
    appId: '1:919198194330:web:dc5c720876e9385a185d23',
    messagingSenderId: '919198194330',
    projectId: 'an-tam-nghe-5d962',
    authDomain: 'an-tam-nghe-5d962.firebaseapp.com',
    storageBucket: 'an-tam-nghe-5d962.firebasestorage.app',
  );
}
