// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAels1gJOV_4nOmweuK9DHXlZRtW66gxbc',
    appId: '1:615527120802:web:b6343d0efcc539548d7cfb',
    messagingSenderId: '615527120802',
    projectId: 'an-tam-nghe',
    authDomain: 'an-tam-nghe.firebaseapp.com',
    storageBucket: 'an-tam-nghe.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBRaJZlb2fLPhOlQnFyln8tc_dU9jWaDK8',
    appId: '1:615527120802:android:a97758756c1f09b48d7cfb',
    messagingSenderId: '615527120802',
    projectId: 'an-tam-nghe',
    storageBucket: 'an-tam-nghe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFxNPfl2P_JA1vEk95Ph9sxru9O_UW81Q',
    appId: '1:615527120802:ios:142d3731e821edb98d7cfb',
    messagingSenderId: '615527120802',
    projectId: 'an-tam-nghe',
    storageBucket: 'an-tam-nghe.firebasestorage.app',
    iosBundleId: 'com.example.antam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFxNPfl2P_JA1vEk95Ph9sxru9O_UW81Q',
    appId: '1:615527120802:ios:142d3731e821edb98d7cfb',
    messagingSenderId: '615527120802',
    projectId: 'an-tam-nghe',
    storageBucket: 'an-tam-nghe.firebasestorage.app',
    iosBundleId: 'com.example.antam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAels1gJOV_4nOmweuK9DHXlZRtW66gxbc',
    appId: '1:615527120802:web:ac1c67e000a145cf8d7cfb',
    messagingSenderId: '615527120802',
    projectId: 'an-tam-nghe',
    authDomain: 'an-tam-nghe.firebaseapp.com',
    storageBucket: 'an-tam-nghe.firebasestorage.app',
  );
}
